// Generated by scripts/vendor-pyena.sh — do not edit by hand.
export const PYENA_COMMIT = "ed788e022ee64730d420d1be4d83b37c1a4cf9a7";
export const PYENA_ARCHIVE = "py/pyena-ed788e0.zip";
/**
 * How displayed figures are styled (bridge.py). Saved figures record it; an
 * analysis saved in an older style is redrawn when it opens. 2: graph paper
 * drawn in the plot's own coordinates; 3: square cells on comparable axes.
 */
export const FIGURE_STYLE = 3;
