#!/bin/sh
# Packages the pyENA library at one pinned commit for the browser engine.
# The worker unpacks this zip into Pyodide's site-packages, so a push to
# pyENA's default branch never changes what the deployed platform computes.
# Usage: npm run vendor:pyena [commit] [path-to-pyENA-checkout]
set -eu
COMMIT="${1:-ed788e0}"
REPO="${2:-$HOME/code/pyENA}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FULL="$(git -C "$REPO" rev-parse "$COMMIT")"
git -C "$REPO" archive "$FULL" src/pyena | tar -x -C "$TMP"
( cd "$TMP/src" && rm -rf pyena/__pycache__ && zip -qrX "$TMP/pyena.zip" pyena )

mkdir -p "$ROOT/public/py" "$ROOT/public/samples"
rm -f "$ROOT"/public/py/pyena-*.zip
cp "$TMP/pyena.zip" "$ROOT/public/py/pyena-$(echo "$FULL" | cut -c1-7).zip"
# The example datasets the library ships, offered as samples in the rail.
git -C "$REPO" show "$FULL:examples/rs/datasets/RS.data.csv" > "$ROOT/public/samples/RS.data.csv"
git -C "$REPO" show "$FULL:examples/gender_ena/datasets/case1/binary_input.csv" > "$ROOT/public/samples/gender_case1_binary_input.csv"
git -C "$REPO" show "$FULL:examples/gender_ena/datasets/case2/binary_input.csv" > "$ROOT/public/samples/gender_case2_binary_input.csv"
# Their coding schemas (code, meaning), offered alongside the datasets.
git -C "$REPO" show "$FULL:examples/gender_ena/datasets/case1/codebook.csv" > "$ROOT/public/samples/gender_case1_codebook.csv"
git -C "$REPO" show "$FULL:examples/gender_ena/datasets/case2/codebook.csv" > "$ROOT/public/samples/gender_case2_codebook.csv"

# The interpretation skill the server gives Claude as its instructions.
mkdir -p "$ROOT/server/skills/interpret-ena-results"
git -C "$REPO" show "$FULL:skills/interpret-ena-results/SKILL.md" > "$ROOT/server/skills/interpret-ena-results/SKILL.md"

cat > "$ROOT/src/engine/version.ts" <<TS
// Generated by scripts/vendor-pyena.sh — do not edit by hand.
export const PYENA_COMMIT = "$FULL";
export const PYENA_ARCHIVE = "py/pyena-$(echo "$FULL" | cut -c1-7).zip";
TS
echo "Vendored pyENA @ $FULL"
